// <auto-generated />
using System;
using DemoDapperPlus.Infrasctructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DemoDapperPlus.Migrations
{
    [DbContext(typeof(PessoaDbContext))]
    partial class PessoaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DemoDapperPlus.Entities.Documento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PessoaId")
                        .HasColumnType("uuid");

                    b.Property<string>("UF")
                        .IsRequired()
                        .HasColumnType("varchar(2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CPF")
                        .HasDatabaseName("IX_Documento_Bairro");

                    b.HasIndex("PessoaId")
                        .IsUnique();

                    b.HasIndex("UF")
                        .HasDatabaseName("IX_Documento_UF");

                    b.ToTable("Documento", (string)null);
                });

            modelBuilder.Entity("DemoDapperPlus.Entities.Endereco", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Complemento")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("varchar(2)");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasColumnType("varchar(120)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<Guid>("PessoaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Bairro")
                        .HasDatabaseName("IX_Endereco_Bairro");

                    b.HasIndex("Cep")
                        .HasDatabaseName("IX_Endereco_Cep");

                    b.HasIndex("Complemento")
                        .HasDatabaseName("IX_Endereco_Complemento");

                    b.HasIndex("Logradouro")
                        .HasDatabaseName("IX_Endereco_Logradouro");

                    b.HasIndex("Numero")
                        .HasDatabaseName("IX_Endereco_Numero");

                    b.HasIndex("PessoaId");

                    b.HasIndex("Cidade", "Estado");

                    b.ToTable("Endereco", (string)null);
                });

            modelBuilder.Entity("DemoDapperPlus.Entities.Pessoa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Idade")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Idade")
                        .HasDatabaseName("IX_Pessoa_Idade");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Pessoa_Name");

                    b.ToTable("Pessoa", (string)null);
                });

            modelBuilder.Entity("DemoDapperPlus.Entities.Documento", b =>
                {
                    b.HasOne("DemoDapperPlus.Entities.Pessoa", "Pessoa")
                        .WithOne("Documento")
                        .HasForeignKey("DemoDapperPlus.Entities.Documento", "PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("DemoDapperPlus.Entities.Endereco", b =>
                {
                    b.HasOne("DemoDapperPlus.Entities.Pessoa", "Pessoa")
                        .WithMany("Enderecos")
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("DemoDapperPlus.Entities.Pessoa", b =>
                {
                    b.Navigation("Documento")
                        .IsRequired();

                    b.Navigation("Enderecos");
                });
#pragma warning restore 612, 618
        }
    }
}
